USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150

INGREDIENT_NAME_MAX_LENGTH = 128
RECIPE_NAME_MAX_LENGTH = 256
UNIT_MAX_LENGTH = 64
MIN_INGREDIENT_AMOUNT = 1
MIN_COOKING_TIME = 1

MIN_AMOUNT = 1
PAGE_SIZE = 6 