# User model constants
USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150

# Recipe model constants
INGREDIENT_NAME_MAX_LENGTH = 128
RECIPE_NAME_MAX_LENGTH = 256
UNIT_MAX_LENGTH = 64
MIN_INGREDIENT_AMOUNT = 1
MIN_COOKING_TIME = 1

# API constants
MIN_AMOUNT = 1
AMOUNT_ERROR = 'Количество ингредиента должно быть больше нуля'
PAGE_SIZE = 6 